# Generated by Django 2.2.2 on 2019-06-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acolhe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='anfitriao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anfitriao', to='acolhe.Anfitriao'),
        ),
    ]
