# Generated by Django 2.2.2 on 2019-06-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acolhe', '0002_anfitriao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anfitriao',
            name='descricao',
        ),
    ]
