# Generated by Django 2.2.2 on 2019-06-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acolhe', '0003_remove_anfitriao_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=120)),
                ('bairro', models.CharField(max_length=120)),
                ('rua', models.CharField(max_length=120)),
                ('numero', models.PositiveIntegerField()),
                ('vagas', models.PositiveIntegerField(default=1)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('OCUPADO', 'ocupado'), ('DISPONIVEL', 'disponível')], default='DISPONIVEL', max_length=20)),
            ],
        ),
    ]
